language: python
env:
  global:
    - CI=true

matrix:
  include:
    - os: linux
      python: 3.6
      
    - os: linux
      python: 3.5
      
    - os: linux
      python: 2.7

install: |
  pip install -e .[test]

script: python tests/plassets_tests.py

# after_success:
# - ./.travis/upload_coverage.sh

branches:
  only:
    - master
